services:
  # MoonTV 核心服务
  - type: web
    name: moontv-core
    runtime: image
    image:
      url: ghcr.io/moontechlab/lunatv:latest
    plan: free # 您可以根据需求选择付费计划
    healthCheckPath: /
    envVars:
      - key: USERNAME
        value: monsoon # 替换为您的站长账号
      - key: PASSWORD
        value: kkb123 # 替换为您的站长密码
      - key: NEXT_PUBLIC_STORAGE_TYPE
        value: kvrocks
      - key: KVROCKS_URL
        fromService:
          type: pserv
          name: moontv-kvrocks
          property: connectionString
      - key: AUTH_TOKEN
        value: f27f52d7825f5bb4b8af0363fcc244cb # 替换为您从机器人获取的授权码
      - key: TZ # 可选：设置时区
        value: Asia/Shanghai

  # Kvrocks 数据库服务
  - type: pserv
    name: moontv-kvrocks
    runtime: image
    image:
      url: apache/kvrocks
    plan: free # 您可以根据需求选择付费计划
    disk:
      name: kvrocks-data
      mountPath: /var/lib/kvrocks
      sizeGB: 1
