services:
  # MoonTV 核心服务
  - type: web
    name: moontv-core
    runtime: image
    image:
      url: ghcr.io/moontechlab/lunatv:latest
    plan: free
    healthCheckPath: /
    envVars:
      - key: USERNAME
        value: monsoon # 替换为您的站长账号
      - key: PASSWORD
        value: kkb123 # 替换为您的站长密码
      - key: NEXT_PUBLIC_STORAGE_TYPE
        value: upstash # 存储类型改为 upstash
      - key: UPSTASH_URL
        value: https://noble-halibut-56987.upstash.io # 替换为您从 Upstash 复制的 URL
      - key: UPSTASH_TOKEN
        value: Ad6bAAIncDE0MGE5Mzg0NDJkNmE0NGVlOTI4Y2UyYzYxZmQ3YTgzMXAxNTY5ODc # 替换为您从 Upstash 复制的 TOKEN
      - key: AUTH_TOKEN
        value: f27f52d7825f5bb4b8af0363fcc244cb # 替换为您从机器人获取的授权码
      - key: TZ
        value: Asia/Shanghai
